# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "cl is a way to group all your aliases, once in a while or multiple usages
with a lot of args commands in an organized and human readable place
"
  homepage "https://github.com/rvigo/cl"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/cl/releases/download/v0.9.0/cl_0.9.0_darwin_amd64.tar.gz"
      sha256 "4275d655c1db3212b256078af46d614175deccb6a3976be1cc81812d540eb336"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/cl/releases/download/v0.9.0/cl_0.9.0_darwin_arm64.tar.gz"
      sha256 "7912b2f42c7fcbe2325366888ca12481a1cff8d2ab46505946fa9a014746b895"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/cl/releases/download/v0.9.0/cl_0.9.0_linux_amd64.tar.gz"
      sha256 "4c3b392a0f1aaa13c6e2979d698fe10ce0e264bbb3038858dac2559bfa051d56"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/cl/releases/download/v0.9.0/cl_0.9.0_linux_arm64.tar.gz"
      sha256 "e629a60cf5826cb61bffb1b934c710d41f2672eb26816eacb9cd1242e2a8b8e6"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  def caveats
    <<~EOS
      In order to get cl completion (only available for ZSH shell),
      be sure that $(brew --prefix)/share/zsh/site-functions is present in $FPATH.
      If not, add the following line to your ~/.zshrc, BEFORE any call to compinit:
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    EOS
  end
end
