# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cl < Formula
  desc "cl is a way to group all your aliases, once in a while or multiple usages
with a lot of args commands in an organized and human readable place
"
  homepage "https://github.com/rvigo/cl"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/cl/releases/download/v0.9.3/cl_0.9.3_darwin_arm64.tar.gz"
      sha256 "7ca3bf8a5f89e1ca2d35f60ad7ae902d6ce95ae3491a5aa2571d8f51569184b2"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/cl/releases/download/v0.9.3/cl_0.9.3_darwin_amd64.tar.gz"
      sha256 "c54f96bfe7d6799af81883638bdb23c2b3ea5948ddb7b037798ce1fb9000e95e"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/cl/releases/download/v0.9.3/cl_0.9.3_linux_arm64.tar.gz"
      sha256 "19b393ccdb7a8f804e2a529ffd37d3d8e83722b0ce7a0cef83fc35e8ed004624"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/cl/releases/download/v0.9.3/cl_0.9.3_linux_amd64.tar.gz"
      sha256 "f5e7d2ecaf8a5a7b4a83faffe82145f7d37c38d9b50bcc877efa316cd0899ef3"

      def install
        bin.install "cl"
        zsh_completion.install "completions/zsh/_cl" => "_cl"
      end
    end
  end

  def caveats
    <<~EOS
      In order to get cl completion (only available for ZSH shell),
      be sure that $(brew --prefix)/share/zsh/site-functions is present in $FPATH.
      If not, add the following line to your ~/.zshrc, BEFORE any call to compinit:
      FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    EOS
  end
end
